on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: saludos
        uses: ./
        with:
          myInput: 'Carlos Rembao'
      - name: output
        run: |
          echo ${{ steps.saludos.output.memory }}
          echo "total memory successful"
